import { Inter } from "next/font/google";
import "./globals.css";
import '@mantine/carousel/styles.css';
import Navbar from '@/components/navbar'
import { MantineProvider } from '@mantine/core';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Intro NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={inter.className}>
          <MantineProvider>
            <Navbar />
            {children}
          </MantineProvider>
        </body>
    </html>
  );
}
