import { Inter } from "next/font/google";
import "./globals.css";
import {ToastContainer} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Navbar from '@/components/navbar'
import ReduxProvider from '@/providers/reduxProvider';
import TanstackProvider from "@/providers/tanstackProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <TanstackProvider>
            <Navbar />
            <ToastContainer />
            {children}
          </TanstackProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
